version: '2.3'

networks:
  monitor-net:

volumes:
    prometheus_data:
    grafana_data:

services:

  traefik:
    image: traefik:latest
    restart: always
    ports: 
      - 8080:8080
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
      - $PWD/ssl/:/ssl/
      - /data/traefik/:/var/log/traefik
    command: traefik --web --web.metrics.prometheus --web.metrics.prometheus.buckets="0.1,0.3,1.2,5.0" --docker --entryPoints='Name:https Address::443 TLS:/ssl/noc.crt,/ssl/noc.key' #--accesslogsfile=/var/log/traefik/access.log
    labels:
      traefik.protocol: http
      "traefik.port": "8080"
      "traefik.backend": manager
      "traefik.frontend.rule": Host:traefik_selectel.sem.net
      "traefik.frontend.entryPoints": https
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
      - '--web-external-url=https://xxx'
    restart: unless-stopped
    networks:
      - monitor-net
    labels:
      traefik.protocol: http
      "traefik.port": "9090"
      "traefik.backend": prometheus
      "traefik.frontend.rule": Host:prometheus.sem.net
      "traefik.frontend.entryPoints": https
      "traefik.network": "front"
      traefik.frontend.headers.STSPreload: "True"
      traefik.frontend.headers.forceSTSHeader: "True"
      traefik.frontend.headers.STSSeconds: "315360000"

  blackboxexporter:
    image: bitnami/blackbox-exporter:latest
    container_name: blackboxexporter
    volumes:
      - ./blackbox/:/etc/blackbox_exporter/
      - /etc/ssl/certs/:/etc/ssl/certs/:ro
    command:
      - '--config.file=/etc/blackbox_exporter/blackbox.yml'
    restart: unless-stopped
    ports:
      - "9115:9115"
    networks:
      - monitor-net

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - monitor-net
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    labels:
      traefik.protocol: http
      "traefik.port": "9093"
      "traefik.backend": alertmanager
      "traefik.frontend.rule": Host:alertmanager.sem.net
      "traefik.frontend.entryPoints": https
      "traefik.network": "front"
      traefik.frontend.headers.STSPreload: "True"
      traefik.frontend.headers.forceSTSHeader: "True"
      traefik.frontend.headers.STSSeconds: "315360000"
      
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=please_change_me
      - GF_SECURITY_ADMIN_PASSWORD=please_change_me
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    labels:
      traefik.protocol: http
      "traefik.port": "3000"
      "traefik.backend": grafana
      "traefik.frontend.rule": Host:grafana.sem.net
      "traefik.frontend.entryPoints": https
      "traefik.network": "front"
      traefik.frontend.headers.STSPreload: "True"
      traefik.frontend.headers.forceSTSHeader: "True"
      traefik.frontend.headers.STSSeconds: "315360000"
    networks:
      - monitor-net
